# Default configuration for sw64-softmmu

# Uncomment the following lines to disable these optional devices:
#
#CONFIG_PCI_DEVICES=n
#CONFIG_TEST_DEVICES=n

# Boards:
#
CONFIG_CORE3=y
CONFIG_CORE4=y
CONFIG_ACPI=y
CONFIG_ACPI_MEMORY_HOTPLUG=y
CONFIG_ACPI_CPU_HOTPLUG = y
CONFIG_ACPI_SW64_PM=y
CONFIG_ACPI_PCI=y
CONFIG_MEM_DEVICE=y
CONFIG_DIMM=y
CONFIG_PCI_EXPRESS_GENERIC_BRIDGE=y
